{
"HAS_PROPERTY": [

    ["COLLECTIVE BIOTIC ENTITY", "BIOTIC PROPERTY"],
    ["COLLECTIVE BIOTIC ENTITY", "SPACIAL PROPERTY"],
    ["COLLECTIVE BIOTIC ENTITY", "TEMPORAL PROPERTY"],

    ["COLLECTIVE ABIOTIC ENTITY", "BIOTIC PROPERTY"],
    ["COLLECTIVE ABIOTIC ENTITY", "SPACIAL PROPERTY"],
    ["COLLECTIVE ABIOTIC ENTITY", "TEMPORAL PROPERTY"],

    ["BIOTIC ENTITY", "BIOTIC PROPERTY"],
    ["BIOTIC ENTITY", "SPACIAL PROPERTY"],
    ["BIOTIC ENTITY", "TEMPORAL PROPERTY"],

    ["ABIOTIC ENTITY", "ABIOTIC PROPERTY"],
    ["ABIOTIC ENTITY", "SPACIAL PROPERTY"],
    ["ABIOTIC ENTITY", "TEMPORAL PROPERTY"],

    ["ANTHROPOGENIC ENTITY", "ANTHROPOGENIC PROPERTY"],
    ["ANTHROPOGENIC ENTITY", "SPACIAL PROPERTY"],
    ["ANTHROPOGENIC ENTITY", "TEMPORAL PROPERTY"],

    ["SPATIAL ENTITY", "SPATIAL PROPERTY"],
    ["TEMPORAL ENTITY", "TEMPORAL PROPERTY"],

    ["ANTHROPOGENIC PROPERTY", "ANTHROPOGENIC PROPERTY"],
    ["BIOTIC PROPERTY", "BIOTIC PROPERTY"],
    ["ABIOTIC PROPERTY", "ABIOTIC PROPERTY"],

  ],
"IS_PART_OF": [

    ["BIOTIC ENTITY", "BIOTIC COLLECTIVE ENTITY"],
    ["ABIOTIC ENTITY", "ABIOTIC COLLECTIVE ENTITY"],

    ["BIOTIC ENTITY", "BIOTIC ENTITY"],
    ["ABIOTIC ENTITY", "ABIOTIC ENTITY"],
    ["ANTHROPOGENIC ENTITY", "ANTHROPOGENIC ENTITY"],

    ["SPATIAL ENTITY", "SPATIAL ENTITY"],
    ["TEMPORAL ENTITY", "TEMPORAL ENTITY"]

  ],
"LOCATED_IN": [

    ["BIOTIC ENTITY", "SPATIAL ENTITY"],
    ["BIOTIC ENTITY", "TEMPORAL ENTITY"],

    ["ABIOTIC ENTITY", "SPATIAL ENTITY"],
    ["ABIOTIC ENTITY", "TEMPORAL ENTITY"],

    ["ANTHROPOGENIC ENTITY", "SPATIAL ENTITY"],
    ["ANTHROPOGENIC ENTITY", "TEMPORAL ENTITY"],

    ["COLLECTIVE BIOTIC ENTITY", "SPATIAL ENTITY"],
    ["COLLECTIVE BIOTIC ENTITY", "TEMPORAL ENTITY"],

    ["COLLECTIVE ABIOTIC ENTITY", "SPATIAL ENTITY"],
    ["COLLECTIVE ABIOTIC ENTITY", "TEMPORAL ENTITY"],

    ["BIOTIC PROCESS", "SPATIAL ENTITY"],
    ["BIOTIC PROCESS", "TEMPORAL ENTITY"],
    ["ABIOTIC PROCESS", "SPATIAL ENTITY"],
    ["ABIOTIC PROCESS", "TEMPORAL ENTITY"],
    ["ANTHROPOGENIC PROCESS", "SPATIAL ENTITY"],
    ["ANTHROPOGENIC PROCESS", "TEMPORAL ENTITY"]

  ],
"IS_AFFECTING": [

    ["ANTHROPOGENIC PROCESS", "ANTHROPOGENIC PROPERTY"],
    ["BIOTIC PROCESS", "BIOTIC PROPERTY"],
    ["ABIOTIC PROCESS", "ABIOTIC PROPERTY"],

    ["ANTHROPOGENIC PROCESS", "BIOTIC COLLECTIVE ENTITY"],
    ["ANTHROPOGENIC PROCESS", "ABIOTIC COLLECTIVE ENTITY"],

    ["ANTHROPOGENIC PROCESS", "BIOTIC ENTITY"],
    ["ANTHROPOGENIC PROCESS", "BIOTIC PROCESS"],
    ["ANTHROPOGENIC PROCESS", "BIOTIC PROPERTY"],

    ["ANTHROPOGENIC PROCESS", "ABIOTIC ENTITY"],
    ["ANTHROPOGENIC PROCESS", "ABIOTIC PROCESS"],
    ["ANTHROPOGENIC PROCESS", "ABIOTIC PROPERTY"],

    ["BIOTIC PROCESS", "BIOTIC COLLECTIVE ENTITY"],
    ["BIOTIC PROCESS", "BIOTIC ENTITY"],
    ["BIOTIC PROCESS", "BIOTIC PROCESS"],
    ["BIOTIC PROCESS", "ABIOTIC COLLECTIVE ENTITY"],
    ["BIOTIC PROCESS", "ABIOTIC ENTITY"],
    ["BIOTIC PROCESS", "ABIOTIC PROCESS"],
    ["BIOTIC PROCESS", "ANTHROPOGENIC ENTITY"],
    ["BIOTIC PROCESS", "ANTHROPOGENIC PROPERTY"],
    ["BIOTIC PROCESS", "ANTHROPOGENIC PROCESS"],

    ["ABIOTIC PROCESS", "ABIOTIC COLLECTIVE ENTITY"],
    ["ABIOTIC PROCESS", "ABIOTIC ENTITY"],
    ["ABIOTIC PROCESS", "ABIOTIC PROCESS"],
    ["ABIOTIC PROCESS", "BIOTIC COLLECTIVE ENTITY"],
    ["ABIOTIC PROCESS", "BIOTIC ENTITY"],
    ["ABIOTIC PROCESS", "BIOTIC PROCESS"],
    ["ABIOTIC PROCESS", "ANTHROPOGENIC ENTITY"],
    ["ABIOTIC PROCESS", "ANTHROPOGENIC PROPERTY"],
    ["ABIOTIC PROCESS", "ANTHROPOGENIC PROCESS"],

    ["BIOTIC ENTITY", "BIOTIC PROCESS"],
    ["BIOTIC ENTITY", "ABIOTIC PROCESS"],
    ["BIOTIC ENTITY", "ANTHROPOGENIC PROCESS"],
    ["BIOTIC ENTITY", "BIOTIC PROPERTY"],
    ["BIOTIC ENTITY", "ABIOTIC PROPERTY"],
    ["BIOTIC ENTITY", "ANTHROPOGENIC PROPERTY"],

    ["BIOTIC PROPERTY", "BIOTIC PROCESS"],
    ["BIOTIC PROPERTY", "ABIOTIC PROCESS"],
    ["BIOTIC PROPERTY", "ANTHROPOGENIC PROCESS"],
    ["ABIOTIC PROPERTY", "BIOTIC PROCESS"],
    ["ABIOTIC PROPERTY", "ABIOTIC PROCESS"],
    ["ABIOTIC PROPERTY", "ANTHROPOGENIC PROCESS"],

    ["ABIOTIC ENTITY", "BIOTIC PROCESS"],
    ["ABIOTIC ENTITY", "ABIOTIC PROCESS"],
    ["ABIOTIC ENTITY", "ANTHROPOGENIC PROCESS"],
    ["ANTHROPOGENIC ENTITY", "BIOTIC PROCESS"],
    ["ANTHROPOGENIC ENTITY", "ABIOTIC PROCESS"],
    ["ANTHROPOGENIC ENTITY", "ANTHROPOGENIC PROCESS"],


    ["ANTHROPOGENIC PROPERTY", "BIOTIC PROCESS"],
    ["ANTHROPOGENIC PROPERTY", "ABIOTIC PROCESS"],
    ["ANTHROPOGENIC PROPERTY", "ANTHROPOGENIC PROCESS"],
    ["ANTHROPOGENIC PROCESS", "BIOTIC PROPERTY"],
    ["ANTHROPOGENIC PROCESS", "ABIOTIC PROPERTY"],
    ["ANTHROPOGENIC PROCESS", "ANTHROPOGENIC PROPERTY"]
]
}
