{
  "HAS PROPERTY": [
    ["BIOTIC ENTITY", "BIOTIC PROPERTY"],
    ["BIOTIC ENTITY", "SPATIAL ENTITY"],
    ["ABIOTIC ENTITY", "ABIOTIC PROPERTY"],
    ["BIOTIC PROCESS", "TEMPORAL PROPERTY"],
    ["ABIOTIC PROCESS", "TEMPORAL PROPERTY"]

  ],
  "IS PART OF": [
    ["BIOTIC ENTITY", "BIOTIC COLLECTIVE ENTITY"]
  ],
  "IS AFFECTED BY": [
    ["BIOTIC ENTITY", "ANTHROPOGENIC PROCESS"],
    ["BIOTIC PROCESS", "ANTHROPOGENIC PROCESS"]
  ],
  "IS DETERMINING": [
    ["ANTHROPOGENIC PROCESS", "ABIOTIC PROPERTY"],
    ["ANTHROPOGENIC PROCESS", "ABIOTIC PROCESS"]
  ]
}
