{
"HAS_PROPERTY": [
    ["BIOTIC ENTITY", "BIOTIC PROPERTY"],
    ["BIOTIC ENTITY", "SPATIAL PROPERTY"],
    ["BIOTIC ENTITY", "TEMPORAL PROPERTY"],
    ["BIOTIC ENTITY", "QUALITATIVE PROPERTY"],
    ["BIOTIC ENTITY", "QUANTITATIVE PROPERTY"],

    ["ABIOTIC ENTITY", "ABIOTIC PROPERTY"],
    ["ABIOTIC ENTITY", "SPATIAL PROPERTY"],
    ["ABIOTIC ENTITY", "TEMPORAL PROPERTY"],
    ["ABIOTIC ENTITY", "QUALITATIVE PROPERTY"],
    ["ABIOTIC ENTITY", "QUANTITATIVE PROPERTY"],

    ["ANTHROPOGENIC ENTITY", "ANTHROPOGENIC PROPERTY"],
    ["ANTHROPOGENIC ENTITY", "SPATIAL PROPERTY"],
    ["ANTHROPOGENIC ENTITY", "TEMPORAL PROPERTY"],
    ["ANTHROPOGENIC ENTITY", "QUALITATIVE PROPERTY"],
    ["ANTHROPOGENIC ENTITY", "QUANTITATIVE PROPERTY"],

    ["SPATIAL ENTITY", "SPATIAL PROPERTY"],
    ["SPATIAL ENTITY", "QUALITATIVE PROPERTY"],
    ["SPATIAL ENTITY", "QUANTITATIVE PROPERTY"],
    ["TEMPORAL ENTITY", "TEMPORAL PROPERTY"],
    ["TEMPORAL ENTITY", "QUALITATIVE PROPERTY"],
    ["TEMPORAL ENTITY", "QUANTITATIVE PROPERTY"],

    ["ANTHROPOGENIC PROPERTY", "ANTHROPOGENIC PROPERTY"],
    ["ANTHROPOGENIC PROPERTY", "QUALITATIVE PROPERTY"],
    ["ANTHROPOGENIC PROPERTY", "QUANTITATIVE PROPERTY"],

    ["BIOTIC PROPERTY", "BIOTIC PROPERTY"],
    ["BIOTIC PROPERTY", "QUALITATIVE PROPERTY"],
    ["BIOTIC PROPERTY", "QUANTITATIVE PROPERTY"],

    ["ABIOTIC PROPERTY", "ABIOTIC PROPERTY"],
    ["ABIOTIC PROPERTY", "QUALITATIVE PROPERTY"],
    ["ABIOTIC PROPERTY", "QUANTITATIVE PROPERTY"],

    ["BIOTIC PROCESS", "BIOTIC PROPERTY"],
    ["BIOTIC PROCESS", "QUALITATIVE PROPERTY"],
    ["BIOTIC PROCESS", "QUANTITATIVE PROPERTY"],

    ["ABIOTIC PROCESS", "ABIOTIC PROPERTY"],
    ["ABIOTIC PROCESS", "QUALITATIVE PROPERTY"],
    ["ABIOTIC PROCESS", "QUANTITATIVE PROPERTY"],

    ["ANTHROPOGENIC PROCESS", "ANTHROPOGENIC PROPERTY"],
    ["ANTHROPOGENIC PROCESS", "QUALITATIVE PROPERTY"],
    ["ANTHROPOGENIC PROCESS", "QUANTITATIVE PROPERTY"],

  ],
"IS_PART_OF": [
    ["BIOTIC ENTITY", "BIOTIC ENTITY"],
    ["ABIOTIC ENTITY", "ABIOTIC ENTITY"],
    ["ANTHROPOGENIC ENTITY", "ANTHROPOGENIC ENTITY"],

    ["SPATIAL ENTITY", "SPATIAL ENTITY"],
    ["TEMPORAL ENTITY", "TEMPORAL ENTITY"]

  ],
"LOCATED_IN": [

    ["BIOTIC ENTITY", "SPATIAL ENTITY"],
    ["BIOTIC ENTITY", "TEMPORAL ENTITY"],

    ["ABIOTIC ENTITY", "SPATIAL ENTITY"],
    ["ABIOTIC ENTITY", "TEMPORAL ENTITY"],

    ["ANTHROPOGENIC ENTITY", "SPATIAL ENTITY"],
    ["ANTHROPOGENIC ENTITY", "TEMPORAL ENTITY"],

    ["BIOTIC PROCESS", "SPATIAL ENTITY"],
    ["BIOTIC PROCESS", "TEMPORAL ENTITY"],
    ["ABIOTIC PROCESS", "SPATIAL ENTITY"],
    ["ABIOTIC PROCESS", "TEMPORAL ENTITY"],
    ["ANTHROPOGENIC PROCESS", "SPATIAL ENTITY"],
    ["ANTHROPOGENIC PROCESS", "TEMPORAL ENTITY"]

  ],
"IS_AFFECTING": [
    ['ANTHROPOGENIC PROCESS', 'ANTHROPOGENIC PROCESS'],
    ['ANTHROPOGENIC PROCESS', 'ABIOTIC PROCESS'],
    ['ANTHROPOGENIC PROCESS', 'BIOTIC PROCESS'],
    ['ABIOTIC PROCESS', 'ANTHROPOGENIC PROCESS'],
    ['ABIOTIC PROCESS', 'ABIOTIC PROCESS'],
    ['ABIOTIC PROCESS', 'BIOTIC PROCESS'],
    ['BIOTIC PROCESS', 'ANTHROPOGENIC PROCESS'],
    ['BIOTIC PROCESS', 'ABIOTIC PROCESS'],
    ['BIOTIC PROCESS', 'BIOTIC PROCESS'],

    ["ANTHROPOGENIC PROCESS", "ANTHROPOGENIC PROPERTY"],
    ["ANTHROPOGENIC PROCESS", "ABIOTIC PROPERTY"],
    ["ANTHROPOGENIC PROCESS", "BIOTIC PROPERTY"],
    ["ANTRHOPOGENIC PROCESS", "QUALITATIVE PROPERTY"],
    ["ANTHROPOGENIC PROCESS", "QUANTITATIVE PROPERTY"],

    ["BIOTIC PROCESS", "ANTHROPOGENIC PROPERTY"],
    ["BIOTIC PROCESS", "ABIOTIC PROPERTY"],
    ["BIOTIC PROCESS", "BIOTIC PROPERTY"],
    ["BIOTIC PROCESS", "QUALITATIVE PROPERTY"],
    ["BIOTIC PROCESS", "QUANTITATIVE PROPERTY"],

    ["ABIOTIC PROCESS", "ANTHROPOGENIC PROPERTY"],
    ["ABIOTIC PROCESS", "ABIOTIC PROPERTY"],
    ["ABIOTIC PROCESS", "BIOTIC PROPERTY"],
    ["ABIOTIC PROCESS", "QUALITATIVE PROPERTY"],
    ["ABIOTIC PROCESS", "QUANTITATIVE PROPERTY"],

    ["ANTHROPOGENIC PROCESS", "ANTHROPOGENIC PROCESS"],
    ["ABIOTIC PROCESS", "ABIOTIC PROCESS"],
    ["BIOTIC PROCESS", "BIOTIC PROCESS"],

    ["ANTHROPOGENIC PROCESS", "ANTHROPOGENIC ENTITY"],
    ["ANTHROPOGENIC PROCESS", "ABIOTIC ENTITY"],
    ["ANTHROPOGENIC PROCESS", "BIOTIC ENTITY"],
    ["ANTHROPOGENIC PROCESS", "SPATIAL ENTITY"],
    ["ANTHROPOGENIC PROCESS", "TEMPORAL ENTITY"],

    ["BIOTIC PROCESS", "ANTHROPOGENIC ENTITY"],
    ["BIOTIC PROCESS", "ABIOTIC ENTITY"],
    ["BIOTIC PROCESS", "BIOTIC ENTITY"],
    ["BIOTIC PROCESS", "SPATIAL ENTITY"],
    ["BIOTIC PROCESS", "TEMPORAL ENTITY"],

    ["ABIOTIC PROCESS", "ANTHROPOGENIC ENTITY"],
    ["ABIOTIC PROCESS", "ABIOTIC ENTITY"],
    ["ABIOTIC PROCESS", "BIOTIC ENTITY"],
    ["ABIOTIC PROCESS", "SPATIAL ENTITY"],
    ["ABIOTIC PROCESS", "TEMPORAL ENTITY"]
]
}
