pid /tmp/nginx.pid;   # <- write PID somewhere writable

events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  access_log    off;

  include /etc/nginx/conf.d/*.conf;
}
