; /etc/supervisor/conf.d/supervisord.conf
[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/nginx.out.log
stderr_logfile=/var/log/supervisor/nginx.err.log

[program:streamlit]
; adjust path to your script if different
command=/bin/bash -lc "streamlit run /app/streamlit_app_annotate.py --server.address ${STREAMLIT_SERVER_ADDRESS} --server.port ${STREAMLIT_SERVER_PORT}"
directory=/app
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/streamlit.out.log
stderr_logfile=/var/log/supervisor/streamlit.err.log
